import type { Metadata } from "next";
import { DM_Sans, Inter, Plus_Jakarta_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/ReduxProvider";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const PlusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-Plus-Jakarta-Sans",
  subsets: ["latin"],
});
const PlayfairDisplay = Playfair_Display({
  variable: "--font-Playfair-Display",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "StudPay - Student Payment Management System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.variable} ${inter.variable} ${PlusJakartaSans.variable} ${PlayfairDisplay.variable} antialiased`}>
          <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
